info:
   foo: bar

management:
   endpoint:
      health:
         show-details: always

logging:
   pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %magenta([%thread]) %red(%X{traceID}) %highlight(%-5level) %logger.%M - %msg%n"
   level:
      root: INFO
      com:
         example: DEBUG         