management:
   endpoints:
      web:
         exposure:
            include: info,health,metrics
   metrics:
      export:
         simple:
            enabled: true
   endpoint:
      health:
         show-details: always

logging:
   pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %magenta([%thread]) %red(%X{traceId}) %highlight(%-5level) %logger{39} - %msg%n"
   level:
      root: INFO
      com:
         example: DEBUG