info:
   foo: bar

management:
   endpoint:
      health:
         show-details: always

logging:
   pattern:
      console: \%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %X{traceID} %highlight(%-5level) %logger.%M - %msg%n
   level:
      root: INFO
      com:
         example: DEBUG