spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_l0ztD18V1
  datasource:
    url: jdbc:mysql://localhost:3306/defaultdatabase?useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
jpa:
  properties:
    hibernate:
      format_sql: false
  show-sql: false
